# Introduction to NumPy

In [1]:
import numpy as np

## Creating arrays

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [7]:
a[2]

3

In [8]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [12]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dementional arrays

In [13]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
n[0][1]

2

In [17]:
n[0][1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [18]:
n[1]

array([4, 5, 6])

In [19]:
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [22]:
n[:, 1]

array([20,  5,  1])

In [23]:
n[:]

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [24]:
n[:, 2] = [0, 1, 2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## Randomly generated arrays

In [27]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [28]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [29]:
np.random.seed(2)
np.random.rand(5, 2) * 100

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [31]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [33]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [34]:
a + 1

array([1, 2, 3, 4, 5])

In [35]:
a * 2

array([0, 2, 4, 6, 8])

In [36]:
a * 100

array([  0, 100, 200, 300, 400])

In [37]:
a / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [40]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [41]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [42]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

In [43]:
a / b

array([0.        , 0.69444444, 1.02040816, 1.171875  , 1.2345679 ])

## Comparison operations

In [45]:
a

array([0, 1, 2, 3, 4])

In [44]:
a >= 2

array([False, False,  True,  True,  True])

In [46]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [47]:
a > b

array([False, False,  True,  True,  True])

In [48]:
a[a > b]

array([2, 3, 4])

In [49]:
a[[False, False,  True,  True,  True]]

array([2, 3, 4])

## Summarizing operations

In [50]:
a.min()

0

In [51]:
a.max()

4

In [52]:
a.sum()

10

In [53]:
a.mean()

2.0

In [54]:
a.std()

1.4142135623730951

In [55]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [56]:
n.sum()

35

In [59]:
n.mean()

3.888888888888889