# Linear Algebra Refresher

In [1]:
import numpy as np

## Vector operations

In [34]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

In [11]:
2 * u

array([ 4,  8, 10, 12])

In [10]:
u + v

array([3, 4, 5, 8])

## Multipication

* Vector-vector multiplication
* Matrix-vector multiplication
* Matrix-matrix multiplication

### Vector-vector multiplication (dot product)

This multiplication is not element-wise like we've seen previously.

In [12]:
u * v

array([ 2,  0,  0, 12])

In this instance we are performing an element wise multiplication but then adding up all of the results together.

$$ \Large \sum_{i=1}^{n} u_i v_i $$

In [13]:
sum(u * v)

14

Normally $u$ is usually a column vector and $v$ is a row vector.
In order to multiply them together, you would have to transpose $v$.

$$ \Large v^Tu = \sum_{i=1}^{n} u_i v_i $$
<center><h6>Dot Product</h6></center>

In [28]:
u.shape

(4,)

In [29]:
v.shape

(4,)

In [16]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result += u[i] * v[i]

    return result

In [17]:
vector_vector_multiplication(u, v)

14.0

NumPy already has a way to do this:

In [19]:
u.dot(v)

14

### Matrix-vector multiplication

$$ \Large Uv $$

In [35]:
U = np.array([
    [2, 4, 5, 6], 
    [1, 2, 1, 2], 
    [3, 1, 2, 1]
])
v = np.array([1, 0.5, 2, 1])

The way this works here is pretty much the same as before.
You just have multiply each row at time.

In [36]:
U.shape

(3, 4)

In [37]:
v.shape

(4,)

In [38]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [39]:
matrix_vector_multiplication(U, v)

array([20. ,  6. ,  8.5])

In [40]:
U.dot(v)

array([20. ,  6. ,  8.5])

### Matrix-matrix multiplication

$$ \Large UV $$

In [41]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

In [42]:
U.shape

(3, 4)

In [43]:
V.shape

(4, 3)

In [44]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [45]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [46]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Matrix inverse

* Identity matrix: Usually depicted as $I$ and is a square matrix with the top-left to bottom-right diagonal is all 1's. It is like a number 1 for matrices, whatever you multiply it with you always get the same back.

$$ \Large UI = U or IU = U $$

In [47]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [48]:
I = np.eye(3)

In [49]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [50]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

A matrix inverse is usually depicted as $A^{-1}$

In [51]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [54]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [55]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])